language: go

go:
 - 1.8.3

before_install:
 - mkdir -p "${GOPATH}/bin"
 - curl https://glide.sh/get | bash

install:
 - glide install

script:
 - cp config_server.yaml.example config_server.yaml
 - make run &
 - cp config_client.yaml.example config_client.yaml
 - make test
